In [119]:
import pandas as pd
import numpy as np
from google.colab import files
file = files.upload()  #upload file into google colab session
df = pd.read_csv("NYPD_Arrest_Data__Year_to_Date_.csv")
df

Saving NYPD_Arrest_Data__Year_to_Date_.csv to NYPD_Arrest_Data__Year_to_Date_ (6).csv


ARREST_KEY ARREST_DATE  PD_CD                         PD_DESC  KY_CD  \
0        238013474  12/18/2021  157.0                          RAPE 1  104.0   
1        236943583  11/25/2021  263.0                     ARSON 2,3,4  114.0   
2        234938876  10/14/2021  594.0                     OBSCENITY 1  116.0   
3        234788259  10/11/2021  263.0                     ARSON 2,3,4  114.0   
4        234188790  09/28/2021  578.0                             NaN    NaN   
...            ...         ...    ...                             ...    ...   
155502   222884924  01/10/2021  397.0  ROBBERY,OPEN AREA UNCLASSIFIED  105.0   
155503   223918625  02/03/2021  792.0        WEAPONS POSSESSION 1 & 2  118.0   
155504   224323770  02/13/2021  101.0                       ASSAULT 3  344.0   
155505   222599533  01/04/2021  792.0        WEAPONS POSSESSION 1 & 2  118.0   
155506   224056881  02/06/2021  268.0              CRIMINAL MIS 2 & 3  121.0   

                             OFNS_DESC    LAW_CODE LAW_CAT_CD ARREST_BORO  \
0                                 RAPE  PL 1303501          F           Q   
1                                ARSON  PL 1501500          F           K   
2                           SEX CRIMES  PL 2631100          F           K   
3                                ARSON  PL 1501001          F           B   
4                                  NaN  PL 2223001          M           B   
...                                ...         ...        ...         ...   
155502                         ROBBERY  PL 1601001          F           B   
155503               DANGEROUS WEAPONS  PL 2650303          F           K   
155504    ASSAULT 3 & RELATED OFFENSES  PL 1200001          M           S   
155505               DANGEROUS WEAPONS  PL 2650303          F           K   
155506  CRIMINAL MISCHIEF & RELATED OF  PL 1451000          F           Q   

        ARREST_PRECINCT  JURISDICTION_CODE AGE_GROUP PERP_SEX  \
0                   105                 97     18-24        M   
1                    69                 71     25-44        M   
2                    61                  0     25-44        M   
3                    42                 71     18-24        M   
4                    44                  0     25-44        M   
...                 ...                ...       ...      ...   
155502               46                  0     45-64        M   
155503               67                  0     18-24        M   
155504              121                  0     45-64        M   
155505               73                  0     25-44        M   
155506              102                  0     18-24        M   

                       PERP_RACE  X_COORD_CD  Y_COORD_CD   Latitude  \
0                          BLACK     1057636      203954  40.726187   
1                          BLACK     1014340      171320  40.636868   
2                          WHITE      995244      155739  40.594145   
3                          BLACK     1009058      239616  40.824340   
4                          BLACK     1005169      246667  40.843703   
...                          ...         ...         ...        ...   
155502                     BLACK     1011432      247605  40.846260   
155503                     BLACK     1004940      180941  40.663302   
155504                     BLACK      942825      166367  40.623227   
155505                     BLACK     1007524      188555  40.684194   
155506  ASIAN / PACIFIC ISLANDER     1031414      190787  40.690226   

        Longitude                       New Georeferenced Column  
0      -73.735234   POINT (-73.73523390399998 40.72618713000002)  
1      -73.891586   POINT (-73.89158591899997 40.63686750900007)  
2      -73.960415   POINT (-73.96041495199995 40.59414516900005)  
3      -73.910365   POINT (-73.91036538099996 40.82433953100008)  
4      -73.924395   POINT (-73.92439508899997 40.84370255600004)  
...           ...                                            ...  
155502 -73.901755  

In [120]:
df.shape

(155507, 19)

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155507 entries, 0 to 155506
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   ARREST_KEY                155507 non-null  int64  
 1   ARREST_DATE               155507 non-null  object 
 2   PD_CD                     155478 non-null  float64
 3   PD_DESC                   155404 non-null  object 
 4   KY_CD                     155404 non-null  float64
 5   OFNS_DESC                 155404 non-null  object 
 6   LAW_CODE                  155507 non-null  object 
 7   LAW_CAT_CD                154114 non-null  object 
 8   ARREST_BORO               155507 non-null  object 
 9   ARREST_PRECINCT           155507 non-null  int64  
 10  JURISDICTION_CODE         155507 non-null  int64  
 11  AGE_GROUP                 155507 non-null  object 
 12  PERP_SEX                  155507 non-null  object 
 13  PERP_RACE                 155507 non-null  o

In [217]:
Model_data=df.copy()
Model_data

ARREST_KEY ARREST_DATE  PD_CD                         PD_DESC  KY_CD  \
0        238013474  12/18/2021  157.0                          RAPE 1  104.0   
1        236943583  11/25/2021  263.0                     ARSON 2,3,4  114.0   
2        234938876  10/14/2021  594.0                     OBSCENITY 1  116.0   
3        234788259  10/11/2021  263.0                     ARSON 2,3,4  114.0   
4        234188790  09/28/2021  578.0                             NaN    NaN   
...            ...         ...    ...                             ...    ...   
155502   222884924  01/10/2021  397.0  ROBBERY,OPEN AREA UNCLASSIFIED  105.0   
155503   223918625  02/03/2021  792.0        WEAPONS POSSESSION 1 & 2  118.0   
155504   224323770  02/13/2021  101.0                       ASSAULT 3  344.0   
155505   222599533  01/04/2021  792.0        WEAPONS POSSESSION 1 & 2  118.0   
155506   224056881  02/06/2021  268.0              CRIMINAL MIS 2 & 3  121.0   

                             OFNS_DESC    LAW_CODE LAW_CAT_CD ARREST_BORO  \
0                                 RAPE  PL 1303501          F           Q   
1                                ARSON  PL 1501500          F           K   
2                           SEX CRIMES  PL 2631100          F           K   
3                                ARSON  PL 1501001          F           B   
4                                  NaN  PL 2223001          M           B   
...                                ...         ...        ...         ...   
155502                         ROBBERY  PL 1601001          F           B   
155503               DANGEROUS WEAPONS  PL 2650303          F           K   
155504    ASSAULT 3 & RELATED OFFENSES  PL 1200001          M           S   
155505               DANGEROUS WEAPONS  PL 2650303          F           K   
155506  CRIMINAL MISCHIEF & RELATED OF  PL 1451000          F           Q   

        ARREST_PRECINCT  JURISDICTION_CODE AGE_GROUP PERP_SEX  \
0                   105                 97     18-24        M   
1                    69                 71     25-44        M   
2                    61                  0     25-44        M   
3                    42                 71     18-24        M   
4                    44                  0     25-44        M   
...                 ...                ...       ...      ...   
155502               46                  0     45-64        M   
155503               67                  0     18-24        M   
155504              121                  0     45-64        M   
155505               73                  0     25-44        M   
155506              102                  0     18-24        M   

                       PERP_RACE  X_COORD_CD  Y_COORD_CD   Latitude  \
0                          BLACK     1057636      203954  40.726187   
1                          BLACK     1014340      171320  40.636868   
2                          WHITE      995244      155739  40.594145   
3                          BLACK     1009058      239616  40.824340   
4                          BLACK     1005169      246667  40.843703   
...                          ...         ...         ...        ...   
155502                     BLACK     1011432      247605  40.846260   
155503                     BLACK     1004940      180941  40.663302   
155504                     BLACK      942825      166367  40.623227   
155505                     BLACK     1007524      188555  40.684194   
155506  ASIAN / PACIFIC ISLANDER     1031414      190787  40.690226   

        Longitude                       New Georeferenced Column  
0      -73.735234   POINT (-73.73523390399998 40.72618713000002)  
1      -73.891586   POINT (-73.89158591899997 40.63686750900007)  
2      -73.960415   POINT (-73.96041495199995 40.59414516900005)  
3      -73.910365   POINT (-73.91036538099996 40.82433953100008)  
4      -73.924395   POINT (-73.92439508899997 40.84370255600004)  
...           ...                                            ...  
155502 -73.901755  

In [218]:

# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(Model_data['PERP_SEX'])
 
# printing label
label

 


array([1, 1, 1, ..., 1, 1, 1])

In [219]:
# removing the column 'Purchased' from df
# as it is of no use now.
Model_data.drop("PERP_SEX", axis=1, inplace=True)
 
# Appending the array to our dataFrame
# with column name 'Purchased'
Model_data["PERP_SEX"] = label


In [220]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le1 = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
label1 = le1.fit_transform(Model_data['PERP_RACE'])
 
# printing label
label1

array([2, 2, 5, ..., 2, 2, 1])

In [221]:
# removing the column 'Purchased' from df
# as it is of no use now.
Model_data.drop("PERP_RACE", axis=1, inplace=True)
 
# Appending the array to our dataFrame
# with column name 'Purchased'
Model_data["PERP_RACE"] = label1


In [222]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le2 = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
label2 = le2.fit_transform(Model_data['AGE_GROUP'])
 
# printing label
label2

array([0, 1, 1, ..., 2, 1, 0])

In [223]:
# removing the column 'Purchased' from df
# as it is of no use now.
Model_data.drop("AGE_GROUP", axis=1, inplace=True)
 
# Appending the array to our dataFrame
# with column name 'Purchased'
Model_data["AGE_GROUP"] = label2

In [224]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le3 = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
label3 = le3.fit_transform(Model_data['ARREST_BORO'])
 
# printing label
label3

array([3, 1, 1, ..., 4, 1, 3])

In [225]:
# removing the column 'Purchased' from df
# as it is of no use now.
Model_data.drop("ARREST_BORO", axis=1, inplace=True)
 
# Appending the array to our dataFrame
# with column name 'Purchased'
Model_data["ARREST_BORO"] = label3


In [226]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le4 = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
label4 = le4.fit_transform(Model_data['OFNS_DESC'])
 
# printing label
label4

array([56,  5, 58, ...,  6, 13, 10])

In [227]:
# removing the column 'Purchased' from df
# as it is of no use now.
Model_data.drop("OFNS_DESC", axis=1, inplace=True)
 
# Appending the array to our dataFrame
# with column name 'Purchased'
Model_data["OFNS_DESC"] = label4

In [230]:
Dropped_model_data=Model_data.drop(['LAW_CAT_CD','PD_CD','KY_CD','PD_DESC','ARREST_DATE','New Georeferenced Column', 'LAW_CODE'],axis=1)

In [231]:
Dropped_model_data.isnull().sum()

ARREST_KEY           0
ARREST_PRECINCT      0
JURISDICTION_CODE    0
X_COORD_CD           0
Y_COORD_CD           0
Latitude             0
Longitude            0
PERP_SEX             0
PERP_RACE            0
AGE_GROUP            0
ARREST_BORO          0
OFNS_DESC            0
dtype: int64

In [232]:
Dropped_model_data

ARREST_KEY  ARREST_PRECINCT  JURISDICTION_CODE  X_COORD_CD  \
0        238013474              105                 97     1057636   
1        236943583               69                 71     1014340   
2        234938876               61                  0      995244   
3        234788259               42                 71     1009058   
4        234188790               44                  0     1005169   
...            ...              ...                ...         ...   
155502   222884924               46                  0     1011432   
155503   223918625               67                  0     1004940   
155504   224323770              121                  0      942825   
155505   222599533               73                  0     1007524   
155506   224056881              102                  0     1031414   

        Y_COORD_CD   Latitude  Longitude  PERP_SEX  PERP_RACE  AGE_GROUP  \
0           203954  40.726187 -73.735234         1          2          0   
1           171320  40.636868 -73.891586         1          2          1   
2           155739  40.594145 -73.960415         1          5          1   
3           239616  40.824340 -73.910365         1          2          0   
4           246667  40.843703 -73.924395         1          2          1   
...            ...        ...        ...       ...        ...        ...   
155502      247605  40.846260 -73.901755         1          2          2   
155503      180941  40.663302 -73.925425         1          2          0   
155504      166367  40.623227 -74.149227         1          2          2   
155505      188555  40.684194 -73.916085         1          2          1   
155506      190787  40.690226 -73.829932         1          1          0   

        ARREST_BORO  OFNS_DESC  
0                 3         56  
1                 1          5  
2                 1         58  
3                 0          5  
4                 0         63  
...             ...        ...  
155502            0         57  
155503            1         13  
155504            4          6  
155505            1         13  
155506            3         10  

[155507 rows x 12 columns]

In [233]:
Dropped_model_data.describe()

ARREST_KEY  ARREST_PRECINCT  JURISDICTION_CODE    X_COORD_CD  \
count  1.555070e+05    155507.000000      155507.000000  1.555070e+05   
mean   2.304676e+08        62.850322           0.912486  1.004996e+06   
std    4.628028e+06        35.258605           7.894204  2.152869e+04   
min    2.224711e+08         1.000000           0.000000  9.142140e+05   
25%    2.263289e+08        34.000000           0.000000  9.912230e+05   
50%    2.306202e+08        62.000000           0.000000  1.004222e+06   
75%    2.344524e+08       101.000000           0.000000  1.017119e+06   
max    2.385139e+08       123.000000          97.000000  1.066928e+06   

          Y_COORD_CD       Latitude      Longitude       PERP_SEX  \
count  155507.000000  155507.000000  155507.000000  155507.000000   
mean   208163.457555      40.737994     -73.925113       0.828966   
std     29904.384015       0.082086       0.077640       0.376540   
min    121312.000000      40.499401     -74.251844       0.000000   
25%    185908.000000      40.676902     -73.974837       1.000000   
50%    207067.000000      40.735036     -73.927979       1.000000   
75%    235804.000000      40.813903     -73.881512       1.000000   
max    271820.000000      40.912723     -73.701612       1.000000   

           PERP_RACE      AGE_GROUP    ARREST_BORO      OFNS_DESC  
count  155507.000000  155507.000000  155507.000000  155507.000000  
mean        3.343399       1.132811       1.600577      27.396471  
std         1.809197       0.838019       1.175033      19.333434  
min         0.000000       0.000000       0.000000       0.000000  
25%         2.000000       1.000000       1.000000      10.000000  
50%         2.000000       1.000000       2.000000      19.000000  
75%         5.000000       1.000000       3.000000      45.000000  
max         6.000000       4.000000       4.000000      63.000000

In [234]:
Dropped_model_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155507 entries, 0 to 155506
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   ARREST_KEY         155507 non-null  int64  
 1   ARREST_PRECINCT    155507 non-null  int64  
 2   JURISDICTION_CODE  155507 non-null  int64  
 3   X_COORD_CD         155507 non-null  int64  
 4   Y_COORD_CD         155507 non-null  int64  
 5   Latitude           155507 non-null  float64
 6   Longitude          155507 non-null  float64
 7   PERP_SEX           155507 non-null  int64  
 8   PERP_RACE          155507 non-null  int64  
 9   AGE_GROUP          155507 non-null  int64  
 10  ARREST_BORO        155507 non-null  int64  
 11  OFNS_DESC          155507 non-null  int64  
dtypes: float64(2), int64(10)
memory usage: 14.2 MB


In [235]:
Dropped_model_data.describe()[['JURISDICTION_CODE']]

JURISDICTION_CODE
count      155507.000000
mean            0.912486
std             7.894204
min             0.000000
25%             0.000000
50%             0.000000
75%             0.000000
max            97.000000

In [236]:
def find_outliers_IQR(Dropped_model_data):

   q1=df.quantile(0.25)

   q3=df.quantile(0.75)

   IQR=q3-q1

   outliers = Dropped_model_data[((Dropped_model_data<(q1-1.5*IQR)) | (Dropped_model_data>(q3+1.5*IQR)))]

   return outliers

In [237]:
Dropped_model_data.sort_index(inplace=True)

In [240]:
#First run fare_amount through the function to return a series of the outliers.

outliers = find_outliers_IQR(Dropped_model_data[["JURISDICTION_CODE"]])

print("number of outliers: "+ str(len(outliers)))

print("max outlier value: "+ str(outliers.max()))

print("min outlier value: "+ str(outliers.min()))

#outliers

number of outliers: 155507
max outlier value: JURISDICTION_CODE    97.0
dtype: float64
min outlier value: JURISDICTION_CODE    1.0
dtype: float64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  if __name__ == '__main__':
